// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObfusCal.Infrastructure.Persistence;

#nullable disable

namespace ObfusCal.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428121621_AddPeerApiKeyHash")]
    partial class AddPeerApiKeyHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.BusySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PeerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("BusySlots");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GraphAccessTokenProtected")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<DateTimeOffset?>("GraphConsentGrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GraphRefreshTokenProtected")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<DateTimeOffset?>("GraphTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("GraphTokenLastRefreshedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("CalendarOwners");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwnerPeerMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarOwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarOwnerRef")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PeerConnectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CalendarOwnerId");

                    b.HasIndex("PeerConnectionId");

                    b.ToTable("CalendarOwnerPeerMappings");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.PeerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PeerConnections");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwnerPeerMapping", b =>
                {
                    b.HasOne("ObfusCal.Infrastructure.Persistence.CalendarOwner", "CalendarOwner")
                        .WithMany("PeerMappings")
                        .HasForeignKey("CalendarOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObfusCal.Infrastructure.Persistence.PeerConnection", "PeerConnection")
                        .WithMany("CalendarOwnerMappings")
                        .HasForeignKey("PeerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarOwner");

                    b.Navigation("PeerConnection");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwner", b =>
                {
                    b.Navigation("PeerMappings");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.PeerConnection", b =>
                {
                    b.Navigation("CalendarOwnerMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
