// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObfusCal.Infrastructure.Persistence;

#nullable disable

namespace ObfusCal.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422123339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.BusySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PeerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.ToTable("BusySlots");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.Consultant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.ConsultantPeerMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PeerConnectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("PeerConnectionId");

                    b.ToTable("ConsultantPeerMappings");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.PeerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PeerConnections");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.ConsultantPeerMapping", b =>
                {
                    b.HasOne("ObfusCal.Infrastructure.Persistence.Consultant", "Consultant")
                        .WithMany("PeerMappings")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObfusCal.Infrastructure.Persistence.PeerConnection", "PeerConnection")
                        .WithMany("ConsultantMappings")
                        .HasForeignKey("PeerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("PeerConnection");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.Consultant", b =>
                {
                    b.Navigation("PeerMappings");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.PeerConnection", b =>
                {
                    b.Navigation("ConsultantMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
