// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObfusCal.Infrastructure.Persistence;

#nullable disable

namespace ObfusCal.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.BusySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AttendeeEmails")
                        .HasColumnType("text[]");

                    b.Property<Guid?>("CalendarOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("PeerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarOwnerId");

                    b.HasIndex("PeerId");

                    b.HasIndex("PeerId", "CalendarOwnerId");

                    b.ToTable("BusySlots");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalendarSourcePluginId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GraphAccessTokenProtected")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<DateTimeOffset?>("GraphConsentGrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GraphRefreshTokenProtected")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<DateTimeOffset?>("GraphTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("GraphTokenLastRefreshedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ICloudAppSpecificPasswordProtected")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("ICloudAppleIdProtected")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("ICloudCalendarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool?>("LastSyncSucceeded")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("CalendarOwners");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwnerAvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AttendeeEmails")
                        .HasColumnType("text[]");

                    b.Property<Guid>("CalendarOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarOwnerId");

                    b.HasIndex("CalendarOwnerId", "Start", "End");

                    b.ToTable("CalendarOwnerAvailabilitySlots");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwnerICalFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarOwnerId");

                    b.ToTable("CalendarOwnerICalFeeds");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwnerPeerMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarOwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarOwnerRef")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PeerConnectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CalendarOwnerId");

                    b.HasIndex("PeerConnectionId");

                    b.ToTable("CalendarOwnerPeerMappings");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarSourceInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationJson")
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SecretDataJson")
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalendarOwnerId");

                    b.HasIndex("CalendarOwnerId", "PluginId");

                    b.ToTable("CalendarSourceInstances");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.ObfuscationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarOwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Context")
                        .HasColumnType("integer");

                    b.Property<bool>("MergeBlocks")
                        .HasColumnType("boolean");

                    b.Property<bool>("RemoveAttendees")
                        .HasColumnType("boolean");

                    b.Property<bool>("RemoveDescription")
                        .HasColumnType("boolean");

                    b.Property<bool>("RemoveLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("RemoveTitle")
                        .HasColumnType("boolean");

                    b.Property<bool>("RoundTimes")
                        .HasColumnType("boolean");

                    b.Property<int>("RoundingIntervalMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalendarOwnerId", "Context")
                        .IsUnique();

                    b.ToTable("ObfuscationProfiles");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.PeerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientCertificateThumbprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClientOrganisationName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ClientOrganisationNameNormalized")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("LastSyncSucceeded")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestedByCalendarOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PinnedCertificateThumbprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByCalendarOwnerId", "ClientOrganisationNameNormalized")
                        .IsUnique();

                    b.ToTable("PeerConnections");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwnerICalFeed", b =>
                {
                    b.HasOne("ObfusCal.Infrastructure.Persistence.CalendarOwner", "CalendarOwner")
                        .WithMany("ICalFeeds")
                        .HasForeignKey("CalendarOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarOwner");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwnerPeerMapping", b =>
                {
                    b.HasOne("ObfusCal.Infrastructure.Persistence.CalendarOwner", "CalendarOwner")
                        .WithMany("PeerMappings")
                        .HasForeignKey("CalendarOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObfusCal.Infrastructure.Persistence.PeerConnection", "PeerConnection")
                        .WithMany("CalendarOwnerMappings")
                        .HasForeignKey("PeerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarOwner");

                    b.Navigation("PeerConnection");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarSourceInstance", b =>
                {
                    b.HasOne("ObfusCal.Infrastructure.Persistence.CalendarOwner", "CalendarOwner")
                        .WithMany("CalendarSourceInstances")
                        .HasForeignKey("CalendarOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarOwner");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.ObfuscationProfile", b =>
                {
                    b.HasOne("ObfusCal.Infrastructure.Persistence.CalendarOwner", "CalendarOwner")
                        .WithMany("ObfuscationProfiles")
                        .HasForeignKey("CalendarOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarOwner");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.PeerConnection", b =>
                {
                    b.HasOne("ObfusCal.Infrastructure.Persistence.CalendarOwner", "RequestedByCalendarOwner")
                        .WithMany()
                        .HasForeignKey("RequestedByCalendarOwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RequestedByCalendarOwner");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.CalendarOwner", b =>
                {
                    b.Navigation("CalendarSourceInstances");

                    b.Navigation("ICalFeeds");

                    b.Navigation("ObfuscationProfiles");

                    b.Navigation("PeerMappings");
                });

            modelBuilder.Entity("ObfusCal.Infrastructure.Persistence.PeerConnection", b =>
                {
                    b.Navigation("CalendarOwnerMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
